### ISSUE TITLE
Backlog from private email: unable to create new task

### ISSUE THREAD

**Issue by aliaksandrb** [aliaksandrb/anydo_api#2]
> Hello,
> I'm trying to use your anydo_api in Python to give AnyDo some much needed features. I'm new to Python and I'm hoping you could lend a hand. I can't get Task.create to work despite following your examples. I can see my tasks and even add a note to them but trying to create a new task returns an error.
> If you have the time this is the code I use:
> 
> ```python
> from anydo_api.client import Client
> from anydo_api.task import Task
> from anydo_api.category import Category
> 
> user = Client(email='xxxx@gmail.com', password='yyyy').get_user()
> 
> task = Task.create(user=user,
>                    title='Clean garden',
>                    priority='Normal',
>                    category='Personligt',
>                    repeatingMethod='TASK_REPEAT_OFF')
> ```
> And this produces the error:
> ```python
> Traceback (most recent call last):
>   File "C:/Users/Björn/AppData/Local/Programs/Python/Python36/any.py", line 11, in <module>
>     repeatingMethod='TASK_REPEAT_OFF')
>   File "C:\Users\Björn\AppData\Local\Programs\Python\Python36\lib\site-packages\anydo_api\resource.py", line 175, in create
>     params=params
>   File "C:\Users\Björn\AppData\Local\Programs\Python\Python36\lib\site-packages\anydo_api\request.py", line 27, in post
>     return __base_request(method='post', url=url, **options)
>   File "C:\Users\Björn\AppData\Local\Programs\Python\Python36\lib\site-packages\anydo_api\request.py", line 100, in __base_request
>     __check_response_for_errors(response)
>   File "C:\Users\Björn\AppData\Local\Programs\Python\Python36\lib\site-packages\anydo_api\request.py", line 78, in __check_response_for_errors
>     raise client_error
> anydo_api.errors.InternalServerError: 500 Server Error: INTERNAL SERVER ERROR for url: https://sm-prod2.any.do/me/tasks?includeDeleted=false&includeDone=false
> ```
> Sorry to bother you like this but your API is by far the best I have seen and I would very much like to use it. Thank you for your time creating it!

**Comment by aliaksandrb** [comment]
Was able to reproduce, the problem occurs because of bad-formatted `uuid` generated using `py36`.

Should be fixed by https://github.com/aliaksandrb/anydo_api/commit/f908ebe7830eafd0e68f4e3123ea992575daf07c
